In [9]:
import numpy as np

In [14]:
a= np.array([1,2,4,5,6,7,8,9,10]) #1d array
a

array([ 1, 2, 4, 5, 6, 7, 8, 9, 10])

In [15]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #2d array
a

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]])

In [16]:
a = np.arange(1,100,2)  #array like range func
a

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [30]:
np.zeros(5) # array filled with zeros in 1D martix

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((5,5)) #array folled with zero in 2d matrix

array([[0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.]])

In [32]:
np.ones(5) # array filled with ones in 1D martix

array([1., 1., 1., 1., 1.])

In [33]:
np.ones((3,2)) # array filled with ones in 2D martix

array([[1., 1.],
 [1., 1.],
 [1., 1.]])

In [35]:
np.linspace(1,10,5) # values that are spaced linearly in a specified interval:

array([ 1. , 3.25, 5.5 , 7.75, 10. ])

In [37]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)                               #quik sort in ascending order

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
np.argsort(arr) #which is an indirect sort along a specified axis

array([1, 0, 3, 5, 2, 6, 4, 7])

In [44]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.searchsorted(arr,5)   #find elements in a sorted array

2

In [48]:
np.partition(arr,2)  #it is a partial sort.

array([1, 2, 3, 5, 7, 4, 6, 8])

In simple words, **`np.partition(arr, 2`**) will split the array arr into two parts, one with elements less than or equal to the element at index 2, and the other with elements greater than or equal to the element at index 2. The resulting array will have the element at index 2 as the pivot.

In [51]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
np.concatenate((a,b))          #You can concatenate them with np.concatenate()

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [56]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x,y),axis=0)      #You can concatenate them on index too

array([[1, 2],
 [3, 4],
 [5, 6]])

In [57]:
np.identity(4) 
#creates an identity matrix of size 4x4.

array([[1., 0., 0., 0.],
 [0., 1., 0., 0.],
 [0., 0., 1., 0.],
 [0., 0., 0., 1.]])

**`np.identity(4)`** is a function in the NumPy library that creates an identity matrix of size 4x4. An identity matrix is a square matrix that has ones along the main diagonal (top-left to bottom-right) and zeroes everywhere else.

In [60]:
np.random.rand(3,2)  #To get any random matrix

array([[0.31595431, 0.91840834],
 [0.07865472, 0.26489172],
 [0.44390808, 0.60845607]])

In [63]:
np.random.randint(0,10) #random integer it gives random integer between 0 to 10

7

In [68]:
a = np.arange(50)
reshaped = a.reshape(5,10) #it will reshapes the array a into a new shape
reshaped

array([[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

So, the above code will create a `1-D` array of shape `(50,)` with elements from **0** to **49**, and then it will reshape it into a `2-D` array of shape `(5,10)` with **5** rows and 10 columns. Each row will have 10 elements, so the first row will be **[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]**, the second row will be **[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]**, and so on.

In [74]:
a = np.arange(20)
a

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
 17, 18, 19])

In [71]:
a.max() # to get max value from array

19

In [72]:
a.min() # to get min value from array

0

In [73]:
a.mean() # to get mean of array

9.5

In [76]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [78]:
array_example.ndim #To find the number of dimensions of the array

3

In [79]:
array_example.size #To find the total number of elements in the array

24

In [81]:
array_example.shape  #And to find the shape of your array

(3, 2, 4)

**`Reshape an array`**

In [82]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [84]:
a.reshape(3,2)

array([[0, 1],
 [2, 3],
 [4, 5]])

In [85]:
#in np.reshape, you can specify a few optional parameters:-
np.reshape(a,newshape=(2,3))

array([[0, 1, 2],
 [3, 4, 5]])

In [89]:
np.reshape(a,newshape=(1,6),order='C')

array([[0, 1, 2, 3, 4, 5]])

**`a`** is the array to be reshaped.

**`newshape`** is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

**`order`**:**` C`** means to read/write the elements using C-like index order, **`F`** means to read/write the elements using Fortran-like index order, **`A`** means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

In [97]:
x= np.array([1,2,5,6,7,8,10,3])    #Indexing / Slicing
x[4]

7

In [98]:
x[0:2]

array([1, 2])

In [99]:
x[1:]

array([ 2, 5, 6, 7, 8, 10, 3])

In [103]:
x[-3:]

array([ 8, 10, 3])

In [120]:
p=x
p[:]=50   # to change all value to original array not a copy
p

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
 [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [122]:
x # ex

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
 [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [104]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [105]:
(a[a>5])

array([ 6, 7, 8, 9, 10, 11, 12])

In [107]:
data = (a>=5)
data

array([[False, False, False, False],
 [ True, True, True, True],
 [ True, True, True, True]])

In [110]:
divisible_by = a[a%2==0]
divisible_by

array([ 2, 4, 6, 8, 10, 12])

In [111]:
not_divisible_by = a[a%2!=0]
not_divisible_by

array([ 1, 3, 5, 7, 9, 11])

In [115]:
a =np.array([1,2,3,4,5,6,7,8,9])
c= a[(a>2)&(a<7)]
c

array([3, 4, 5, 6])

In [116]:
c= (a>5)|(a==5)
c

array([False, False, False, False, True, True, True, True, True])

In [117]:
x = np.arange(1, 25).reshape(2, 12) 
x

array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [136]:
l = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
l[0][1] # 0 is the index of raw and 1 is the index of column

2

In [137]:
l[1] #it's returning the 1st index from the raws

array([ 6, 7, 8, 9, 10])

In [145]:
# advance 
l[:2,1:]

array([[ 2, 3, 4, 5],
 [ 7, 8, 9, 10]])

In [144]:
l[:0,2:]

array([[1, 2, 3, 4, 5]])